name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build with Buildozer
        # Using the official Kivy-friendly builder to avoid the 'user' error
        uses: akshayaurora/buildozer-action@master
        with:
          buildozer_version: master
          command: buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: LearnIt-Package
          path: bin/*.apk
